[build]
  command = "npm install --force && npx puppeteer browsers install chrome &&  npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--force"
  NETLIFY_USE_YARN = "false"

[functions]
  node_bundler = "esbuild"