
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--force"
  NETLIFY_USE_YARN = "false"
  PUPPETEER_CACHE_DIR = "/opt/buildhome/.cache/puppeteer"

[functions]
external_node_modules = ["@sparticuz/chromium"]

[functions."update-database"]
schedule = "00 01 * * *"
  