[build.environment]
  NODE_VERSION = "20"
  PLAYWRIGHT_BROWSERS_PATH = "0" # Garante que os navegadores sejam baixados no build
  NPM_FLAGS = "--force"
  NETLIFY_USE_YARN = "false"

[functions]
  external_node_modules = ["playwright"]

[functions."update-database"]
  schedule = "00 01 * * *"